/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "stm32f0xx.h"

void peripherals_init(void);

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    /* Loop forever */
	for(;;);
}


/**
 * @brief: This function initializes the peripheral clock on GPIO ports
 * A, B and C and enables the pins:
 * 		PA4, PB0 as output
 * 		PC0, PC1 as pullup input
 *
 * 	and initializes the interrupt
 *
 * @param: none
 * @returns: none
 */
__INLINE void peripherals_init(void){
	RCC->AHBENR |= RCC_AHBENR_GPIOAEN | RCC_AHBENR_GPIOBEN | RCC_AHBENR_GPIOCEN; /* enable clock */
	GPIOA->MODER |= GPIO_MODER_MODER4_0;
	GPIOB->MODER |= GPIO_MODER_MODER0_0;
	GPIOC->PUPDR |= GPIO_PUPDR_PUPDR0_0;
	GPIOC->PUPDR |= GPIO_PUPDR_PUPDR1_0;
}
